remoteDir="https://raw.githubusercontent.com/zamstation/dart_package_template/main/scripts"
remoteDir2="https://raw.githubusercontent.com/zamstation/temp/main"
localDir="temp"
mkdir -p "$localDir"
echo "Downloading Scripts from $remoteDir to $localDir ..."
curl -o "$localDir/logger.sh" "$remoteDir/logger.sh"
curl -o "$localDir/error_thrower.sh" "$remoteDir/error_thrower.sh"
curl -o "$localDir/test.sh" "$remoteDir/test.sh"
curl -o "$localDir/abc.sh" "$remoteDir2/abc.sh"
cat "$localDir/abc.sh"
ls -l "$localDir"
echo "Running Scripts ..."
# sh "$localDir/test.sh"
sh "$localDir/abc.sh"
echo "Removing Scripts ..."
rm -rf "$localDir"
