name: temp
version: 0.1.1
description: Core library for all zamstation packages which contains the most
  basic classes like the NamedException to get started.
homepage: https://zamstation.com
repository: https://github.com/zamstation/temp

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.4
