name: zam_temp1
version: 0.1.1
description: A dummy package that is used, internally by the Zamstation team, in the testing of automated dart package deployment.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_temp1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.4
