remoteDir="https://raw.githubusercontent.com/zamstation/dart_package_template/main/scripts"
localDir="./.temp"
mkdir -p "$localDir"
echo "Downloading Scripts ..."
touch "a.txt"
echo "hi" > "a.txt"
ls -l
cat "a.txt"
curl -o "$localDir/logger.sh" "$remoteDir/logger.sh"
curl -o "$localDir/error_thrower.sh" "$remoteDir/error_thrower.sh"
curl -o "$localDir/test.sh" "$remoteDir/test.sh"