name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:  
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:      
      # - name: Checkout Code
      #   uses: actions/checkout@v2

      # - name: Use Cache or Download
      #   run: | 
      #     echo "::set-output name=CACHE_KEY::$(cat projectFile | grep -Po '(?<=Version>).*(?=</Version>)')"

      - name: Download Scripts
        run: bash download.sh

      - name: Cache Scripts
        # id: scripts-cache
        uses: actions/cache@v2
        with:
          path: temp
          key: scripts-cache-key-2

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Extract Scripts From Cache
        # id: scripts-cache
        uses: actions/cache@v2
        with:
          path: temp
          key: scripts-cache-key-2

      - name: Validate
        run: |
          pwd
          ls -ltr
          ls -ltr temp
          bash temp/publish.sh
