name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Download Scripts
        run: bash download.sh

      - name: Validate
        run: pwd
          ls -ltr
          bash .temp/validate.sh
