name: Build

on:
  push:
    branches-ignore: ["ignore"]
  pull_request:
    branches-ignore: ["ignore"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: workspace/code
      - name: Build
        uses: zamstation/dart_package_deployer/actions/build@temp
      - name: Export Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: build-${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Import Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: build-${{ github.sha }}
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: Dry Deploy
        uses: zamstation/dart_package_deployer/actions/deploy@temp
