name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Download:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Scripts
        run: bash download.sh

      - name: Cache Scripts
        # id: scripts-cache
        uses: actions/cache@v2
        with:
          path: temp
          key: scripts-cache-key

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: [Download]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Extract Scripts From Cache
        # id: scripts-cache
        uses: actions/cache@v2
        with:
          path: temp
          key: scripts-cache-key

      - name: Validate
        run: |
          pwd
          ls -ltr
          ls -ltr temp
          bash temp/validate.sh
