name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    env:
      CI_CD_REPO: https://raw.githubusercontent.com/zamstation/dart_package_ci_cd/main
    steps:
      - name: Extract Cache Key
        id: extract-cache-key
        run: |
          cacheKey=$(curl -s $CI_CD_REPO/version.txt)
          echo "Cache Key: $cacheKey"
          echo "::set-output name=CACHE_KEY::$cacheKey"

      - name: Cache Scripts
        id: cache-scripts
        uses: actions/cache@v2
        with:
          path: temp
          key: ${{ steps.extract-cache-key.outputs.CACHE_KEY }}

      - name: Download Scripts
        if: steps.cache-scripts.outputs.cache-hit != 'true'
        run: bash <(curl -s $CI_CD_REPO/download.sh)

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: [prepare]
    env:
      CI_CD_REPO: https://raw.githubusercontent.com/zamstation/dart_package_ci_cd/main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # - name: Extract Cache Key
      #   id: extract-cache-key
      #   run: echo "::set-output name=CACHE_KEY::$(curl -s $CI_CD_REPO/version.txt)"

      - name: Extract Scripts From Cache
        uses: actions/cache@v2
        with:
          path: temp
          key: ${{ jobs.validate.steps.extract-cache-key.outputs.CACHE_KEY }}

      - name: Validate
        run: bash temp/validate.sh
