name: Deploy Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: workspace

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    env:
      DEPLOYER_PUBSPEC: https://raw.githubusercontent.com/zamstation/dart_package_deployer/main/pubspec.yaml
      CACHE_KEY_PREFIX: dart-package-workspace

    steps:
      - name: Extract Cache Key
        id: extract-cache-key
        run: |
          cacheKey="$CACHE_KEY_PREFIX-$(curl -s $DEPLOYER_PUBSPEC | grep "version:" | cut -d":" -f2 | xargs)"
          echo "Cache Key: $cacheKey"
          echo "::set-output name=cacheKey::$cacheKey"
      - name: Extract Workspace From Cache
        id: cache-workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: ${{ steps.extract-cache-key.outputs.cacheKey }}
      - name: Create New Workspace
        if: steps.cache-workspace.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/zamstation/dart_package_deployer.git
          bash dart_package_deployer/bin/main.sh
          rm -rf dart_package_deployer
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: workspace/code
      - name: Show Workspace
        run: |
          echo -e "\nWorkspace Directory:"
          ls -ltra workspace
          echo -e "\nScripts Directory:"
          ls -ltra workspace/deploy/scripts
          echo -e "\Code Directory:"
          ls -ltra workspace/code
      - name: Export Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: prepare-${{ github.sha }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare]
    defaults:
      run:
        working-directory: workspace/code
    steps:
      - name: Import Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: prepare-${{ github.sha }}
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: Compile
        run: bash ../deploy/scripts/compile.sh
      - name: Lint
        run: bash ../deploy/scripts/lint.sh
      - name: Analyze
        run: bash ../deploy/scripts/analyze.sh
      - name: Pack
        working-directory: workspace
        run: bash deploy/scripts/pack.sh code build
      - name: Cleanup
        working-directory: workspace
        run: rm -rf code
      - name: Export Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: build-${{ github.sha }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [prepare]
    defaults:
      run:
        working-directory: workspace/code
    steps:
      - name: Import Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: prepare-${{ github.sha }}
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: Dart Pub Upgrade
        run: pub upgrade
      - name: Test
        run: bash ../deploy/scripts/test.sh

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Import Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: build-${{ github.sha }}
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: Validate
        run: bash deploy/scripts/validate.sh build
      - name: Publish
        run: bash deploy/scripts/publish.sh build
