name: "Deploy"

on:
  push:
    branches: [main]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    env:
      SHELL_UTILITIES_ACCESS_TOKEN: ${{ secrets.SHELL_UTILITIES_ACCESS_TOKEN }}
      COMMIT_SHA: ${{ github.sha }}
    outputs:
      docker_file_list: ${{ steps.export.outputs.docker_file_list }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Create docker files list
        run: bash scripts/list.sh

      - name: Export list
        id: export
        run: echo "::set-output name=docker_file_list::$(cat docker_file_list.txt)"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.docker_file_list != '' }}
    env:
      SHELL_UTILITIES_ACCESS_TOKEN: ${{ secrets.SHELL_UTILITIES_ACCESS_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Deploy
        run: bash scripts/deploy.sh "${{ needs.prepare.outputs.docker_file_list }}"
