name: Deploy Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "false"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: workspace/code
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: Test
        uses: zamstation/dart_package_deployer/actions/test@test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: workspace/code
      - name: Build
        uses: zamstation/dart_package_deployer/actions/build@test
      - name: Export Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: build-${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Import Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: build-${{ github.sha }}
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: Deploy
        uses: zamstation/dart_package_deployer/actions/deploy@test
