name: Deploy Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEPLOYER_PUBSPEC: https://raw.githubusercontent.com/zamstation/dart_package_deployer/main/pubspec.yaml
  CACHE_KEY_PREFIX: dart-package-workspace

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest

    steps:
      - name: Extract Cache Key
        id: extract-cache-key
        run: |
          cacheKey="$CACHE_KEY_PREFIX-$(curl -s $DEPLOYER_PUBSPEC | grep "version:" | cut -d":" -f2 | xargs)"
          echo "Cache Key: $cacheKey"
          echo "::set-output name=cacheKey::$cacheKey"

      - name: Extract Workspace From Cache
        id: cache-workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: ${{ steps.extract-cache-key.outputs.cacheKey }}

      - name: Create New Workspace
        if: steps.cache-workspace.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/zamstation/dart_package_deployer.git
          bash dart_package_deployer/bin/main.sh
          rm -rf dart_package_deployer

      - name: Show Workspace
        run: |
          echo "Workspace Directory:"
          ls -ltra workspace
          echo -e "\nScripts Directory:"
          ls -ltra workspace/deploy/scripts

      - name: Export Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: prepare-${{ github.sha }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - name: Import Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: prepare-${{ github.sha }}

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: workspace/code

      - name: Pack
        run: |
          pwd
          cd workspace
          ls -ltr
          ls -ltra code
          bash deploy/scripts/pack.sh code build

      - name: Export Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: build-${{ github.sha }}

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Import Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: build-${{ github.sha }}

      - name: Install Dart
        uses: dart-lang/setup-dart@v1

      - name: Move to build directory
        run: cd workspace/build

      - name: Compile
        run: bash compile.sh

      - name: Lint
        run: bash lint.sh

      - name: Analyze
        run: bash analyze.sh

      - name: Validate
        run: bash validate.sh

      - name: Export Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: validate-${{ github.sha }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [validate]

    steps:
      - name: Import Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: validate-${{ github.sha }}

      - name: Install Dart
        uses: dart-lang/setup-dart@v1

      - name: Move to build directory
        run: cd workspace/build

      - name: Test
        run: bash test.sh

      - name: Export Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: test-${{ github.sha }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Import Workspace
        uses: actions/cache@v2
        with:
          path: workspace
          key: test-${{ github.sha }}

      - name: Install Dart
        uses: dart-lang/setup-dart@v1

      - name: Move to build directory
        run: cd workspace/build

      - name: Publish
        run: bash publish.sh
